name: 'check feedback'
description: 'check that the feedback lives up to certain requirements'
inputs:
  repo-token:  # id of input
    description: 'Token for the repo'
    required: true
  minimal-wordcount:
    description: The minimal word count requirement for acceptable feedback
    required: true
  remarkable-wordcount:
    description: the minimal word count requirement for remarkable feedback
    required: true  
  deadline:
    description: deadline for the feedback as a string in the ISO 8601 format
    required: true  
runs:
  using: 'node12'
  main: 'index.js'