version: "3.3"

services:
  backend:
    image: kthopen/backend
    ports:
      - 4004:4004
    networks: 
      open-network:
    environment:
      logstash__host: open-logstash
  open-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    ports:
      - 9200:9200
    networks:
      open-network:
  open-logstash:
    command: "logstash --path.settings /tmp -e 'input { tcp { port => 5505 codec => json  }} output { elasticsearch { hosts => \"open-elasticsearch:9200\" }}'"
    image: docker.elastic.co/logstash/logstash-oss:6.0.0
    ports:
      - 5505:5505
    networks:
      open-network:
  open-kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.0.0
    environment:
      ELASTICSEARCH_URL: http://open-elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      open-network:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      open-network:


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
    links:
      - prometheus
    networks:
      open-network:


networks:
  open-network: