name: 'Verify KTH GitHub id'
description: 'Greet someone and record the time'
inputs:
  changed-files:  # id of input
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'