---
title: 'An Introduction to Graph Databases'
author:
- Simon Larsén
date: \today
numbersections: true
csl: ieee.csl
colorlinks: true
link-citations: true
citecolor: black
linkcolor: black
urlcolor: black
toccolor: black
bibliography: ref.bib
geometry: "left=3cm,right=3cm,top=2cm,bottom=2cm"
header-includes:
- \usepackage{graphicx}
- \usepackage{amsfonts}
- \usepackage{booktabs}
- \usepackage{float}
- \usepackage{multicol}
---

