ame: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    types: [opened]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  duplicateDetector:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-python@v2
    with:
      python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
  - run: python course-automation/badal-johennin/.github/workflows/dpd.py
