name: Check valid slides
'on':
  pull_request:
  workflow_dispatch:
jobs:
  changes:
    if: ${{ contains(github.event.*.labels.*.name, 'presentation') }}
    runs-on: ubuntu-latest
    steps:
        - uses: phamelink/check-valid-slides-action@v1.0.1
