name: workflow
on: 
  pull_request:
    paths:
      - '**/feedback/**/README.md'
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#      with:
#        ref: feedbackcheck
    
    - name: check feedback
      id: feedback
      uses: ./contributions/course-automation/augustjo-grunler
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        minimal-wordcount: 500
        remarkable-wordcount: 1000
        deadline: '2021-04-27T23:59Z'
