name: workflow

on: 
  pull_request:
#    paths:
#      - '/contributions/course-automation/**'
#todo: add branch check?
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feedbackcheck
    
    - name: check feedback
      id: feedback
      uses: ./contributions/course-automation/augustjo-grunler
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.feedback.outputs.changed_files}}"