name: workflow

on: 
  pull_request:
#    paths:
#      - './contributions/course-automation/**'
#todo: add branch check?
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feedbackcheck
    
    - name: check feedback
      id: feedback
      uses: ./contributions/course-automation/augustjo-grunler
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
    # Use the output from the `hello` step
    - name: Print number of changed files
      run: |
       echo "Number of changed files ${{ steps.feedback.outputs.changed_files}}" 
       echo "the path to the readme is ${{ steps.feedback.outputs.readme_path}}"
       pip install markdown-word-count
       ::set-output name=word_count::$(mwc ${{steps.feedback.outputs.readme_path}})  
       echo "wordcount of file is ${{steps.feedback.outputs.word_count}}" 