name: Group validity check
on:
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get file added in the pullrequest
        id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - id: getPayload
        run: |
          payload=$(cat $GITHUB_EVENT_PATH)
          payload="${payload//'%'/'%25'}"
          payload="${payload//$'\n'/'%0A'}"
          payload="${payload//$'\r'/'%0D'}"
          echo "::set-output name=payload::$payload"
      - uses: EleonoraBorzis/group-validity-action@main
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          payload:  ${{ steps.getPayload.outputs.payload }}
          filesAdded: ${{ steps.file_changes.outputs.files_added}}
          basefolder: contributions/ 
          maxGroupSize: 3 
          maxCollaborationTimes: 2 
