name: Hemingway feedback

# Controls when the action will run. 
on:
  pull_request:
    branches:
    - "2021"
    paths:
    - "./contributions/essay"
  
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  hemingway:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ./contributions/course-automation/wska-thestar19/requirements.txt ]; then pip install -r ./contributions/course-automation/wska-thestar19/requirements.txt; fi

      # Setup Chrome 
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      
      # Setup Chromedriver
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      # Set timezone to Europe/Stockholm
      - name: Set timezone
        run: sudo timedatectl set-timezone Europe/Stockholm

      # Runs a single command using the runners shell
      - name: Run the hemingway feedback script
        env:
          SUPER_SECRET: ${{ secrets.SECRET_KEY }}

        run: python ./contributions/course-automation/wska-thestar19/main.py $SUPER_SECRET
