# This is a basic workflow to help you get started with Actions


name: Check merge

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - 2022
    types:
      - closed
    paths:
      - contributions/**


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  if_merged:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

     # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install pytz

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '
          fileOutput: ' '

      - name: Check merge
        env:
          REPO_FULLNAME: ${{ github.repository }}
          FILE_CHANGES: ${{ steps.file_changes.outputs.files_added  }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          FILE_CHANGES_2: FILES
          BODY: ${{ github.event.pull_request.body }}
          MERGER: ${{ github.event.pull_request.merged_by.login }}
          DATE_OF_MERGE: ${{ github.event.pull_request.merged_at }}
        run: python ./tools/merge_checker.py
