# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - id: changed-files
      name: Get changed files
      uses: jitterbit/get-changed-files@v1
    
    
    
    - name: Verify location
      id: verify-location
      run: |
        python tools/verify_location.py main ${{ steps.changed-files.outputs.all }}
        
    - name: Verify content
      id: verify-markdown
      uses: bubriks/file-content-checker@0.1.0
      with:
        path: ${{ steps.verify-location.outputs.markdown }}
        structure: >
          {
            "title": [
              "^# presentation:.*$",
              "^# essay:.*$",
              "^# demo:.*$",
              "^# open-source:.*$",
              "^# executable tutorial:.*$",
              "^# course automation:.*$",
              "^# feedback:.*$"
            ],
            "member": {
              "title": "^## members$",
              "memberOne": [
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                  "gitHub": "^github: https://github.com/[a-z]+$"
                },
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                }
              ],
              "memberTwo": [
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                  "gitHub": "^github: https://github.com/[a-z]+$"
                },
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                },
                {}
              ],
              "memberThree": [
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                  "gitHub": "^github: https://github.com/[a-z]+$"
                },
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                },
                {}
              ]
            },
            "proposal": "^## proposal$"
          }

    - name: Verify folder names
      run: |
        python tools/verify_folder_names.py main ${{ steps.verify-markdown.outputs.result }} ${{ steps.verify-location.outputs.categoryfolder }} ${{ steps.verify-location.outputs.memberfolder }}
