# Controls when the workflow will run
on:
  pull_request_target:
    branches:
      - "2022"
    paths:
      - contributions/**

jobs:
  check-slide-links:
    runs-on: ubuntu-latest
    name: Check for valid slides
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.4
      - name: Check for valid slides
        id: check-slides
        uses: phamelink/course-automation-github-action@v1.2.3
        with:
          allFiles: ${{ steps.changed-files.outputs.all_changed_files }}
          token: ${{ secrets.GITHUB_TOKEN }}
