# Controls when the workflow will run
on:
  pull_request_target:
    branches:
      - "2022"
    paths:
      - contributions/**

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref_name }}
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ''
      - name: test
        run: |
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo "---------CREATING VARIABLES--------"
          ADDED_FILES='${{ steps.file_changes.outputs.files_added}}'
          MODIFIED_FILES='${{ steps.file_changes.outputs.files_modified}}'
          echo $ADDED_FILES
          echo $MODIFIED_FILES
          echo $HOME
          echo "-----PWD------"
          pwd
          echo "-------LS------"
          git branch --show-current
          git branch -l
          
          grep "http" $ADDED_FILES $MODIFIED_FILES

# jobs:
#   check-slide-links:
#     runs-on: ubuntu-latest
#     name: Check for valid slides
#     steps:
#       - name: checking out repo
#         uses: actions/checkout@v3
#       - name: Check for valid slides
#         id: check-slides
#         uses: phamelink/course-automation-github-action@v1.2.9
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}

# ls contributions
#           ls contributions/presentation
#           ls contributions/presentation/week2-testing-and-CI
#           ls contributions/presentation/week2-testing-and-CI/test/
