# Controls when the workflow will run
on:
  pull_request_target:
    branches:
      - "2022"
    paths:
      - contributions/**

jobs:
  check-slide-links:
    runs-on: ubuntu-latest
    name: Check for valid slides
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files 
        id: changed-files
        uses: tj-actions/changed-files@v18.4

