# Controls when the workflow will run
on:
  pull_request_target:
    branches:
      - "2022"
    paths:
      - contributions/**

jobs:
  check-slide-links:
    runs-on: ubuntu-latest
    name: Check for valid slides
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Get changed files 1
        id: changed-files
        uses: tj-actions/changed-files@v18.4
      - name: Get changed files 2
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    steps:
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.ts}}
